alertrules:
  criticalEnabled: true
  errorsEnabled: true
  warningsEnabled: true

falco-exporter:
  serviceAccount:
    name: falco-exporter

  podSecurityContext:
    fsGroup: 2000

  serviceMonitor:
    enabled: false

  grafanaDashboard:
    enabled: true
    namespace: falco
    folder: /falco
    prometheusDatasourceName: victoria-metrics

  service:
    annotations:
      prometheus.io/scrape: "false"
