psp:
  enabled: "false"
  privileged: overlay_me

alertrules:
  criticalEnabled: true 
  errorsEnabled: true

falco-exporter:
  podSecurityPolicy:
    create: false

  serviceAccount:
    name: falco-exporter

  podSecurityContext:
    fsGroup: 2000

  serviceMonitor:
    enabled: false

  grafanaDashboard:
    enabled: true
    namespace: falco
    folder: /falco
    prometheusDatasourceName: victoria-metrics

  service:
    annotations:
      prometheus.io/scrape: "false"