alertrules:
  criticalEnabled: true
  errorsEnabled: true

falco-exporter:
  serviceAccount:
    name: falco-exporter

  podSecurityContext:
    fsGroup: 2000

  serviceMonitor:
    enabled: false

  grafanaDashboard:
    enabled: true
    namespace: falco
    folder: /falco
    prometheusDatasourceName: victoria-metrics

  service:
    annotations:
      prometheus.io/scrape: "false"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi