{{- if eq .Values.diskalerts.enabled "true" -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: disk-alerts
spec:
  groups:
    - name: DiskAlerts
      rules:
        - alert: DiskFilling
          expr: 100 * (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 15 and predict_linear(node_filesystem_avail_bytes[6h], 4 * 24 * 3600) < 0
          for: 10m
          labels:
            env: "{{ printf "{{ $labels.kubernetes_namespace }}" }}"
            infrastructure: critical
            alert_with_resolve: "true"
          annotations:
            summary: "Disk full in four days (instance {{ $labels.instance }})"
            description: "{{ printf "{{ $labels.volume }}" }} is expected to fill up within four days. Currently {{ printf "{{ $value | humanize }}" }}% is available.\n VALUE = {{ printf "{{ $value }}" }}\n LABELS: {{ printf "{{ $labels }}" }}"
        - alert: DiskSpaceUsage
          expr: 100.0 - 100 * (node_filesystem_avail_bytes  / node_filesystem_size_bytes) > 95
          for: 10m
          labels:
            env: "{{ printf "{{ $labels.kubernetes_namespace }}" }}"
            infrastructure: critical
            alert_with_resolve: "true"
          annotations:
            summary: "Disk Space Usage (instance {{ printf "{{ $labels.instance }}" }})"
            description: "Disk Space on Drive is used more than 95%\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS: {{ printf "{{ $labels }}" }}"
{{- end -}}