{{- if eq .Values.kubernetesalerts.enabled "true" -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
spec:
  groups:
    - name: KubernetesAlerts
      rules:
        - alert: KubernetesApiServerErrors
          expr: sum(rate(apiserver_request_total{job="apiserver",code=~"^(?:5..)$"}[1m])) / sum(rate(apiserver_request_total{job="apiserver"}[1m])) * 100 > 3
          for: 2m
          labels:
            infrastructure: critical
          annotations:
            summary: Kubernetes API server errors (instance {{ printf "{{ $labels.instance }}" }})
            description: "Kubernetes API server is experiencing high error rate\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesContainerOomKiller
          expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          for: 0m
          labels:
            infrastructure: warning
          annotations:
            summary: Kubernetes container oom killer (instance {{ printf "{{ $labels.instance }}" }})
            description: "Container {{ printf "{{ $labels.container }}" }} in pod {{ printf "{{ $labels.namespace }}" }}/{{ printf "{{ $labels.pod }}" }} has been OOMKilled {{ printf "{{ $value }}" }} times in the last 10 minutes.\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesCronjobSuspended
          expr: kube_cronjob_spec_suspend != 0
          for: 0m
          labels:
            infrastructure: info
          annotations:
            summary: Kubernetes CronJob suspended (instance {{ printf "{{ $labels.instance }}" }})
            description: "CronJob {{ printf "{{ $labels.namespace }}" }}/{{ printf "{{ $labels.cronjob }}" }} is suspended\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesDiskPressure
          expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
          for: 2m
          labels:
            infrastructure: critical
          annotations:
            summary: Kubernetes disk pressure (instance {{ printf "{{ $labels.instance }}" }})
            description: "{{ printf "{{ $labels.node }}" }} has DiskPressure condition\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesJobFailed
          expr: kube_job_status_failed > 0
          for: 0m
          labels:
            infrastructure: info
          annotations:
            summary: Kubernetes Job failed (instance {{ printf "{{ $labels.instance }}" }})
            description: "Job {{ printf "{{$labels.namespace}}" }}/{{ printf "{{$labels.exported_job}}" }} failed to complete\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesVolumeOutOfDiskSpace
          expr: kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 < 10
          for: 2m
          labels:
            infrastructure: critical
          annotations:
            summary: Kubernetes Volume out of disk space (instance {{ printf "{{ $labels.instance }}" }})
            description: "Volume is almost full (< 10% left)\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesMemoryPressure
          expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
          for: 2m
          labels:
            infrastructure: critical
          annotations:
            summary: Kubernetes memory pressure (instance {{ printf "{{ $labels.instance }}" }})
            description: "{{ printf "{{ $labels.node }}" }} has MemoryPressure condition\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesOutOfDisk
          expr: kube_node_status_condition{condition="OutOfDisk",status="true"} == 1
          for: 2m
          labels:
            infrastructure: critical
          annotations:
            summary: Kubernetes out of disk (instance {{ printf "{{ $labels.instance }}" }})
            description: "{{ printf "{{ $labels.node }}" }} has OutOfDisk condition\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
        - alert: KubernetesPersistentvolumeclaimPending
          expr: kube_persistentvolumeclaim_status_phase{phase="Pending"} == 1
          for: 10m
          labels:
            infrastructure: info
          annotations:
            summary: Kubernetes PersistentVolumeClaim pending (instance {{ printf "{{ $labels.instance }}" }})
            description: "PersistentVolumeClaim {{ printf "{{ $labels.namespace }}" }}/{{ printf "{{ $labels.persistentvolumeclaim }}" }} is pending\n  VALUE = {{ printf "{{ $value }}" }}\n  LABELS = {{ printf "{{ $labels }}" }}"
{{- end -}}