{{- if eq .Values.podalerts.enabled "true" -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-alerts
spec:
  groups:
    - name: PodAlerts
      rules:
        - alert: KubePodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total{namespace=~".*"}[5m]) * 60 * 5 > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: Pod is crash looping.
{{- end -}}