kube-state-metrics:
  image:
    registry: registry.k8s.io
    repository: kube-state-metrics/kube-state-metrics
  autosharding:
    enabled: false
  revisionHistoryLimit: 2
  prometheus:
    monitor:
      enabled: true
  selfMonitor:
    enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi