opentelemetry-collector:
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
  presets:
    clusterMetrics:
      enabled: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        # http://victoria-metrics-victoria-metrics-single-server.default.svc.cluster.local:8428/opentelemetry
        # cluster-wide should be vmstorage directly 
        # http://victoria-metrics-cluster-vmstorage.victoria-metrics-cluster:8428/opentelemetry
        # http://victoria-metrics-cluster-vminsert.default:8480/insert/0/prometheus
        endpoint: http://victoria-metrics-cluster-vminsert.default:8480/insert/0/opentelemetry/api/v1/push
        tls:
            insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/victoriametrics]
  clusterRole:
    create: true
  ingress:
    enabled: true
  serviceMonitor:
    enabled: true