apiVersion: v2
name: prometheus-node-exporter
version: 1.0.0
description: This Chart deploys prometheus-node-exporter.
dependencies:
  - name: prometheus-node-exporter
    version: 4.43.1
    repository: https://prometheus-community.github.io/helm-charts
