apiVersion: v2
name: external-secrets
version: 1.0.0
description: This Chart deploys external-secrets secrets.
dependencies:
  - name: external-secrets
    version: "0.18.2"
    repository: https://charts.external-secrets.io
  - name: default-netpol
    version: 1.5.0-3ff8a7
    repository: oci://ghcr.io/hamburg-port-authority/defaultnetpol