opencost:
  opencost:
    exporter:
      securityContext: 
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
    ui:
      # -- Enable OpenCost UI
      enabled: true
      securityContext: 
        capabilities:
          drop:
          - ALL
        # https://github.com/opencost/opencost-helm-chart/issues/198
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1001
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
    metrics:
      serviceMonitor:
        enbaled: true
    prometheus:
      internal:
        enabled: false
      external:
        enabled: true
        url: http://victoria-metrics-cluster-vmselect.victoria-metrics-cluster:8481/select/0/prometheus