opencost:
  # -- Overwrite the default name of the chart
  nameOverride: ""
  # -- Overwrite all resources name created by the chart
  fullnameOverride: ""
  # -- Override the deployment namespace
  namespaceOverride: "opencost"

  opencost:
    exporter:
      securityContext: 
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      extraEnv:
        KUBECOST_SCRAPE_INTERVAL: 1m
        PROM_CLUSTER_ID_LABEL: cluster

    prometheus:
      internal:
        enabled: false
      external:
        enabled: true
        url: http://vmsingle-vm-victoria-metrics-k8s-stack.vm.svc:8429/prometheus

    ui:
      # -- Enable OpenCost UI
      enabled: true
      securityContext: 
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault