grafana:
  rbac:
    create: true
    pspEnabled: true
    pspUseAppArmor: true
    namespaced: false

  serviceAccount:
    create: true
    autoMount: true

  replicas: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: "60"

  deploymentStrategy:
    type: Recreate

  serviceMonitor:
    enabled: true
    path: /metrics

  ingress:
    enabled: true
    ingressClassName: nginx

  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

  initChownData:
    enabled: false

  plugins:
    - digrich-bubblechart-panel
    - grafana-clock-panel

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: victoriametrics
          type: prometheus
          orgId: 1
          url: http://victoria-metrics-cluster-vmselect.victoria-metrics:8481/select/0/prometheus/
          access: proxy
          isDefault: true
          updateIntervalSeconds: 10
          editable: true
        - name: Alertmanager
          type: alertmanager
          url: http://prometheus-alertmanager-headless.victoria-metrics:9093
          access: proxy
          jsonData:
            implementation: prometheus
            manageAlerts: true
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.loki
          jsonData:
            maxLines: 1000
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "1"

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      victoriametrics:
        gnetId: 11176
        revision: 18
        datasource: victoriametrics
      vmagent:
        gnetId: 12683
        revision: 7
        datasource: victoriametrics
      kubernetes:
        gnetId: 14205
        revision: 1
        datasource: victoriametrics
      nodeexporterfull:
        gnetId: 1860
        revision: 30
        datasource: victoriametrics
        
  grafana.ini:
    snapshots:
      external_enabled: false
    analytics:
      check_for_updates: false
      reporting_enabled: false
    security:
      cookie_secure: true
      content_security_policy: true
      disable_gravatar: true
      strict_transport_security: true
    server:
      domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"

  sidecar:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    alerts:
      enabled: false
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      defaultFolderName: null
      searchNamespace: ALL
      watchMethod: WATCH
      folderAnnotation: grafana-folder
      provider:
        folder: "/tmp/dashboards"
        foldersFromFilesStructure: true
    datasources:
      enabled: false
    plugins:
      enabled: false
    notifiers:
      enabled: false

  revisionHistoryLimit: 5
