{{- range .Values.maintainerGroups }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-maintainer
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-maintainer                             
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: sso:{{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}