apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: http-issuer-delete
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["list", "get", "delete"]