#https://github.com/bitnami-labs/sealed-secrets
tls:
  crt: overlay_me_crt
  key: overlay_me_key

sealed-secrets:
  crd:
    create: false
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
    limits:
      memory: 125Mi
      cpu: 50m
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false