{{- if .Values.clientIntent.enabled }}
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: client-intents-for-popeye-cronjob
  namespace: popeye
spec:
  service:
    name: popeye-cronjob
  calls:
    - name: "svc:kubernetes.default"
    - kind: Service
      name: prometheus-pushgateway.prometheus-pushgateway
{{- end }}