popeye:
  
  resources:
    limits:
      cpu: '1'
      memory: 1000Mi
  
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    seccompProfile:
          type: RuntimeDefault

  cronjob:
    outputFormat: prometheus