clientIntent:
  enabled: true
popeye:
  cronJob:
    schedule: "0 * * * *"
    history:
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 0
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    
    containerConfiguration:
      outputFormat: ""

  job:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 5000
      runAsGroup: 5000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    resources:
      limits:
        cpu: '1'
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
  
  grafana:
    enabled: true
    datasource: "victoriametrics"