popeye:
  
  resources:
    limits:
      cpu: '1'
      memory: 1000Mi
  
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 2000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  cronjob:
    outputFormat: prometheus