deployment:
  image: ghcr.io/coveros/webhook-tester:sha-847b6a9

affinity: {}
  # example affinity:
  # nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nodetype
  #           operator: In
  #           values:
  #           - infrastructurenode

tolerations: {}
  # - key: "nodetype"
  #   operator: "Equal"
  #   value: "infrastructurenode"
  #   effect: "NoSchedule"