deployment:
  image: ghcr.io/deb4sh/webhook-tester:edge
  resources:
    requests:
      cpu: 10 #value in m
      memory: 128 #value in Mi
    limits:
      cpu: 50 #value in m
      memory: 256 #value in Mi

affinity: {}
  # example affinity:
  # nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nodetype
  #           operator: In
  #           values:
  #           - infrastructurenode

tolerations: {}
  # - key: "nodetype"
  #   operator: "Equal"
  #   value: "infrastructurenode"
  #   effect: "NoSchedule"