# Levels of falco (https://github.com/falcosecurity/falco-exporter?tab=readme-ov-file#event-priority)
# 7 = debug (ignorable)
# 6 = information (ignorable)
# 5 = notice (ignorable)
# 4 = warning (ignorable)
# 3 = error
# 2 = critical
# 1 = alert
# 0 = emergency

# these warnings are rather filterd and nice to know
---
{{- if .Values.alertrules.warningsEnabled}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: falco-level-warning
spec:
  groups:
    - name: falco-level-warning
      rules:
        - alert: Falco Event Shell in Container
          expr: |
            rate(falco_events{priority="4", rule="shell_in_container"}[1m])
          labels:
            falco: "warning"
            teamsAlert: "true"
          annotations:
            description: "There was a shell created in pod {{ printf "{{ $labels.k8s_ns_name }}" }} / {{ printf "{{ $labels.k8s_pod_name }}" }}. Source: {{ printf "{{ $labels.source }}" }} / {{ printf "{{ $labels.rule }}" }} with tags {{ printf "{{ $labels.tags }}" }}"
            summary: A shell was created within a pod.
{{- end}}