psp:
  privileged: overlay_me

init:
  application:
  - applicationEnabled: true
    path: "./argocd-applicationsets/env/development"
    targetRevision: "main"
    manifestId: "test"
  repository:
  - repositoryEnabled: true
    url: https://github.com/Hamburg-Port-Authority/kubernetes-service-catalog
    username: "overlay_me"
    password: "overlay_me"
    insecure: "false"
    forceHttpBasicAuth: "false"
    externalSecretEnabled: true
    manifestId: "test"
    secretStore: "secret-store"
  externalSecret:
    enabled: false

ingress:
  enabled: "true"
  host: "overlay_me"
  issuer: "overlay_me"
  className: "nginx"
  secretName: ""
  sslPassthrough: ""

argo-cd:
  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    serviceAccount:
      create: true

  controller:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  server:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 90
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 90
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    replicaCount: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
