init:
  application:
    - applicationEnabled: true
      path: "./argocd-applicationsets/env/development"
      targetRevision: "main"
      manifestId: "test"
  repository:
    - repositoryEnabled: true
      url: https://github.com/Hamburg-Port-Authority/kubernetes-service-catalog
      username: "overlay_me"
      password: "overlay_me"
      insecure: "false"
      forceHttpBasicAuth: "false"
      isSshConnection: true
      manifestId: "test"
      secretStore: "secret-store"
  externalSecret:
    enabled: false

ingress:
  enabled: "true"
  host: "overlay_me"
  issuer: "overlay_me"
  className: "nginx"
  secretName: ""
  sslPassthrough: ""

argo-cd:
  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    serviceAccount:
      create: true  
    resources: 
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi

  controller:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 1024Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  server:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 90
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 90
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    replicaCount: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true  
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  dex:
    initImage:
      resources: 
        # Default Values 
        requests:
          cpu: 5m
          memory: 96Mi
        limits:
          cpu: 10m
          memory: 144Mi
    
    # -- Resource limits and requests for dex
    resources: 
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi

  # -- Resource limits and requests for the notifications controller
  notifications:
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

default-netpol:
  netPol:
    enabled: true
    policies:
      - name: "argocd-core-application-controller-default"
        namespace: "argocd"
        egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-redis
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-repo-server
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        policyTypes: 
          - "Egress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-application-controller
      - name: "argocd-core-applicationset-controller-default"
        namespace: "argocd"
        egress:
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        policyTypes: 
          - "Egress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-applicationset-controller
      - name: "argocd-dex-server-default"
        namespace: "argocd"
        egress:
          - to: #hpa-dc-01.ht.stadt.hamburg.de
            - ipBlock:
                cidr: 10.39.64.11/32
            - ipBlock:
                cidr: fd99:44e7:3c49:ef9b::a27:400b/128
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: "argocd-server"
        policyTypes: 
          - "Egress"
          - "Ingress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-dex-server
      - name: "argocd-notification-controller-default"
        namespace: "argocd"
        egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-repo-server
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        policyTypes: 
          - "Egress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-notification-controller
      - name: "argocd-redis-default"
        namespace: "argocd"
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: argocd
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "argocd-repo-server"
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: argocd
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "argocd-application-controller"
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: argocd
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "argocd-server"
        policyTypes: 
          - "Ingress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-redis
      - name: "argocd-redis-secret-init-default"
        namespace: "argocd"
        egress:
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        policyTypes: 
          - "Egress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-redis-secret-init
      - name: "argocd-repo-server-default"
        namespace: "argocd"
        egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  intents.otterize.com/service: argocd-core-redis-argocd-d39ebe
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-redis
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/component: redis
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-redis
          - to:
          # proxy.ht.stadt.hamburg.de
          # tfsprod.trafficmanager.net folgende sind bereits enthalten
          # tfsprodweu10.westeurope.cloudapp.azure.com
          # tfsprodweu2.westeurope.cloudapp.azure.com
          # tfsprodweu3.westeurope.cloudapp.azure.com
          # tfsprodweu4.westeurope.cloudapp.azure.com
          # fsprodweu5.westeurope.cloudapp.azure.com
          # tfsprodweu6.westeurope.cloudapp.azure.com
          # tfsprodweu7.westeurope.cloudapp.azure.com
          # tfsprodweu8.westeurope.cloudapp.azure.com
          # tfsprodweu9.westeurope.cloudapp.azure.com
          # tfsprodweusu4.westeurope.cloudapp.azure.com
            - ipBlock:
                cidr: 172.30.36.122/32
            - ipBlock:
                cidr: 40.74.28.0/32
            - ipBlock:
                cidr: 40.74.28.1/32
            - ipBlock:
                cidr: 40.74.28.12/32
            - ipBlock:
                cidr: 40.74.28.19/32
            - ipBlock:
                cidr: 40.74.28.21/32
            - ipBlock:
                cidr: 40.74.28.27/32
            - ipBlock:
                cidr: 40.74.28.28/32
            - ipBlock:
                cidr: 40.74.28.3/32
            - ipBlock:
                cidr: 40.74.28.31/32
            - ipBlock:
                cidr: 40.74.28.47/32
            - ipBlock:
                cidr: 40.74.28.9/32
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: argocd
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "argocd-application-controller"
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: argocd
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "argocd-server"
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: argocd
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "argocd-notification-controller"
        policyTypes: 
          - "Egress"
          - "Ingress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-repo-server
      - name: "argocd-server-default"
        namespace: "argocd"
        egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-redis
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-repo-server
          - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: argocd
              podSelector:
                matchLabels:
                  app.kubernetes.io/instance: argocd-core
                  app.kubernetes.io/name: argocd-dex-server
          - ports:
            - port: 6443
              protocol: TCP
            to:
            - ipBlock:
                cidr: 10.96.0.1/32
            - ipBlock:
                cidr: 10.13.16.196/32
            - ipBlock:
                cidr: 10.13.16.197/32
            - ipBlock:
                cidr: 10.13.16.199/32
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
        policyTypes: 
          - "Egress"
        podSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-server