apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunnel-{{ .Release.Name }}
  labels:
    app: stunnel-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: stunnel-{{ .Release.Name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stunnel-{{ .Release.Name }}
    spec:
      {{- if .Values.affinity }}
      affinity: 
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end}}
      serviceAccountName: stunnel-{{ .Release.Name }}
      containers:
        - name: stunnel
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: stunnel-{{ .Release.Name }}
          ports:
            - containerPort: 465
              name: smtp
          volumeMounts:
            - mountPath: "/tmp/certs"
              name: ssl
              readOnly: true
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: ssl
          secret:
            secretName: stunnel-{{ .Release.Name }}
      restartPolicy: Always
