apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: alertmanager
spec:
  image:
    repository: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
    pullPolicy: IfNotPresent
  configNamespaceSelector: {}
  configRawYaml: {{ .Values.configRawYaml | toYaml | indent 2}}
  configSelector: {}
  replicaCount: 1
  extraEnvs: 
    {{- .Values.extraEnvs | toYaml | nindent 4 }}
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 250Mi
  useStrictSecurity: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  {{- if .Values.affinity }}
  affinity: 
      {{- toYaml .Values.affinity | nindent 8 }}
  {{- end}}
  {{- if .Values.tolerations }}
  tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
  {{- end }}
