{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-pdns-api-key
  namespace: external-dns
spec:
  data:
    - remoteRef:
        key: pdns-api-key
      secretKey: pdns_api_key
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: external-dns
    template:
      engineVersion: v2
      mergePolicy: Replace
{{- end -}}
