apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: client-intents-for-grafana
  namespace: victoria-metrics
spec:
  service:
    name: grafana
  calls:
    - name: "svc:kubernetes.default"
    - name: loki-gateway.loki
    - name: victoria-metrics-cluster-vmselect.victoria-metrics-cluster
    - type: internet
      internet:
        domains:
          - proxy.ht.stadt.hamburg.de
        ips:
          - 172.30.36.122/32 # proxy.ht.stadt.hamburg.de
{{- if .Values.clientIntent.mssql.enabled -}}
    - type: internet
      internet:
        domains:
          - {{ .Values.clientIntent.mssql.domain }}
{{- end -}}
