{{- if .Values.externalSecret.adminCred.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-grafana-admin-credentials
  namespace: victoria-metrics
spec:
  data:
  - remoteRef:
      key: grafana-admin-password
    secretKey: grafana-admin-password
  - remoteRef:
      key: grafana-admin-user
    secretKey: grafana-admin-user
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: grafana-admin-credentials
    template:
      engineVersion: v2
      mergePolicy: Replace
{{- end -}}
