{{- if .Values.externalSecret.mssql.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-grafana-mssql
  namespace: victoria-metrics
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    name: grafana-mssql
  data:
    - secretKey: grafana-mssql-user
      remoteRef:
        key: grafana-mssql-user
    - secretKey: grafana-mssql-passsword
      remoteRef:
        key: grafana-mssql-passsword
{{- end -}}