{{- if .Values.externalSecret.azureClientSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-gf-auth-azuread-client-secret
  namespace: victoria-metrics
spec:
  data:
  - remoteRef:
      key: gf-auth-azuread-client-secret
    secretKey: GF_AUTH_AZUREAD_CLIENT_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gf-auth-azuread-client-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
{{- end -}}
