{
 "title": "Resource Checker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mem Waste",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n        label_replace(\n            container_memory_working_set_bytes{pod!=\"\", container!=\"\", namespace=~\"$Namespace\"}, \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n        ), \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ) \n) by (exported_pod, exported_namespace)\n/\nsum(kube_pod_container_resource_requests{resource=\"memory\", exported_pod!=\"\"}) by (exported_namespace, exported_pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem waste (in %)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", exported_pod!=\"\"}) by (exported_namespace, exported_pod)\n/\nsum (\n    label_replace(\n        label_replace(\n            container_memory_working_set_bytes{pod!=\"\", container!=\"\", namespace=~\"$Namespace\"}, \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n        ), \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ) \n) by (exported_pod, exported_namespace) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Waste",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(\n    label_replace(\n        label_replace(\n            rate(\n                container_cpu_usage_seconds_total{pod!=\"\", container!=\"\", namespace=~\"$Namespace\"}[1m]\n            ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n        ), \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    )\n) by (exported_pod, exported_namespace) \n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", exported_pod!=\"\"}) by (exported_namespace, exported_pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu waste (in %)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", exported_pod!=\"\"}) by (exported_namespace, exported_pod)\n/\nsum(\n    label_replace(\n        label_replace(\n            rate(\n                container_cpu_usage_seconds_total{pod!=\"\", container!=\"\", namespace=~\"$Namespace\"}[1m]\n            ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n        ), \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    )\n) by (exported_pod, exported_namespace) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}