apiVersion: v2
name: vcluster
version: 1.0.0
description: This Chart deploys vcluster k3s by default.
#vcluster use default k3s
dependencies:
  - name: vcluster
    version: 0.19.4
    repository: https://charts.loft.sh
