kubeclarity:
  vulnerability-scanner:
    ## Analyzer config.
    analyzer:
      ## Space seperated list of analyzers. (syft gomod)
      # analyzerList: "syft gomod"
      analyzerList: "gomod"

      analyzerScope: "squashed"

      trivy:
        ## Enable trivy analyzer, if true make sure to add it to analyzerList above
        ##
        enabled: false
        timeout: "300"

    ## Scanner config.
    scanner:
      ## Space seperated list of scanners. (grype dependency-track)
      scannerList: "grype"

      grype:
        ## Enable grype scanner, if true make sure to add it to scannerList above
        ##
        enabled: true
        ## Grype scanner mode. (LOCAL, REMOTE)
        mode: "REMOTE"

        ## Remote grype scanner config.
        remote-grype:
          timeout: "2m"

      dependency-track:
        ## Enable dependency-track scanner, if true make sure to add it to scannerList above
        ##
        enabled: false
        insecureSkipVerify: "true"
        disableTls: "true"
        apiserverAddress: "dependency-track-apiserver.dependency-track"
        apiKey: ""

      trivy:
        ## Enable trivy scanner, if true make sure to add it to scannerList above.
        ## To guarentee reliable scans, also ensure that the trivy analyzer is enabled.
        ##
        enabled: false
        timeout: "300"

  ## Overrides global.affinity
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # affinity: {}

  ## Overrides global.nodeSelector
  # nodeSelector:
  #   key1: value1

## End of KubeClarity Grype Server Values
#######################################################################################

#######################################################################################
## KubeClarity Trivy Server Values
## https://github.com/aquasecurity/trivy/blob/main/helm/trivy/values.yaml

kubeclarity-trivy-server:
  enabled: false
  ## By default disable requirement for persistent storage
  persistence:
    enabled: false
