metrics:
  tenantName: overlay_me

tenant:
  tenant:
    metrics:
      enabled: true
      port: 9000
      protocol: http
    prometheusOperator: false
    logging:
      anonymous: true
      json: true
      quiet: true
  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    
  ingress:
    api:
      ingressClassName: "nginx"
    console:
      ingressClassName: "nginx"
