kyverno:
  # Admission controller configuration
  admissionController:
    replicas: 1
  # Reports controller configuration
  reportsController:
    replicas: 1
  # Cleanup controller configuration
  cleanupController:
    replicas: 1
  # Background controller configuration
  backgroundController:
    replicas: 1

  # CRDs configuration
  crds:
    # -- Whether to have Helm install the Kyverno CRDs, if the CRDs are not installed by Helm, they must be added before policies can be created
    install: true
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
      strategy.spinnaker.io/replace: "true"
