kyverno:
  # Admission controller configuration
  # admissionController:
  #   replicas: 0
  # # Reports controller configuration
  # reportsController:
  #   replicas: 0
  # # Cleanup controller configuration
  # cleanupController:
  #   replicas: 0
  # # Background controller configuration
  # backgroundController:
  #   replicas: 0

  # CRDs configuration
  crds:
    # -- Whether to have Helm install the Kyverno CRDs, if the CRDs are not installed by Helm, they must be added before policies can be created
    install: true
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
      strategy.spinnaker.io/replace: "true"
  admissionController:
    container:
      resources:
        # -- Pod resource limits
        limits:
          cpu: "200m"
          memory: 128Mi
        # -- Pod resource requests
        requests:
          cpu: 100m
          memory: 64Mi

  backgroundController:
    resources:
    # -- Pod resource limits
      limits:
        cpu: "200m"
        memory: 128Mi
      # -- Pod resource requests
      requests:
        cpu: 100m
        memory: 64Mi
  cleanupController:
    resources:
    # -- Pod resource limits
      limits:
        cpu: "200m"
        memory: 128Mi
      # -- Pod resource requests
      requests:
        cpu: 100m
        memory: 64Mi
  reportsController:
    resources:
      # -- Pod resource limits
      limits:
        cpu: "200m"
        memory: 196Mi
      # -- Pod resource requests
      requests:
        cpu: 100m
        memory: 128Mi
