trivy-operator:
  podSecurityContext: 
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  # fsGroup: 2000

  # -- securityContext security context
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  trivyOperator:
    scanJobPodTemplatePodSecurityContext: 
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    # -- scanJobPodTemplateContainerSecurityContext SecurityContext the user wants the scanner and node collector containers (and their
    # initContainers) to be amended with.
    scanJobPodTemplateContainerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true

  trivy:
    server:
    # -- podSecurityContext set trivy-server podSecurityContext
    podSecurityContext:
      runAsUser: 65534
      runAsNonRoot: true
      fsGroup: 65534

    # -- securityContext set trivy-server securityContext
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      privileged: false
      readOnlyRootFilesystem: true