apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-alertmanager-config-delete-role
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["alertmanagerconfigs"]
  verbs: ["list", "get"]
- apiGroups: ["operator.victoriametrics.com"]
  resources: ["vmalertmanagerconfigs"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]