apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-alertmanager-config-delete-role
rules:
- apiGroups: ["monitoring.coreos.com/v1alpha1"]
  resources: ["AlertmanagerConfig"]
  verbs: ["list"]
- apiGroups: ["operator.victoriametrics.com/v1beta1"]
  resources: ["VMAlertmanagerConfig"]
  verbs: ["list", "delete"]
