apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-alertmanager-config-delete-rolebinding
subjects:
- kind: ServiceAccount
  name: vm-alertmanager-config-delete-sa
  namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: vm-alertmanager-config-delete-role
  apiGroup: rbac.authorization.k8s.io