apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-alertmanager-config-delete-rolebinding
  namespace: {{.Values.namespace}}
subjects:
- kind: ServiceAccount
  name: vm-alertmanager-config-delete-sa
  namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: vm-alertmanager-config-delete-role
  apiGroup: rbac.authorization.k8s.io