# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: victoria-metrics-alert
spec:
  useStrictSecurity: true
  securityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  datasource:
    url: {{ .Values.vmalert.datasource }}
  evaluationInterval: 15s
  extraArgs:
    remoteWrite.disablePathAppend: "true"
  image:
    repository: {{ .Values.image.repository }}
  notifiers:
  - url: {{ .Values.vmalert.notifiers }}
  remoteRead:
    url: {{ .Values.vmalert.remoteRead }}
  remoteWrite:
    url: {{ .Values.vmalert.remoteWrite }}
  selectAllByDefault: true
  {{- if .Values.affinity }}
  affinity: 
      {{- toYaml .Values.affinity | nindent 8 }}
  {{- end}}
  {{- if .Values.tolerations }}
  tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
  {{- end }}

