prometheus-pushgateway:
  ingress:
    enanbled: true
    className: "nginx"

  securityContext:
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
    fsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  persistentVolume:
    enabled: true