prometheus-pushgateway:
  ingress:
    enanbled: true
    className: "nginx"

  securityContext:
    fsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL

  persistentVolume:
    enabled: false