apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-maintainer
rules:
  # core api
  - apiGroups: [""]
    resources: ["pods", "pods/portforward", "pods/ephemeralcontainers", "configmaps", "services"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  - apiGroups: [""]
    resources: ["pods/log", "namespaces", "events", "nodes", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "watch", "list"]
  # autoscaling api
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # apps api
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # batch api
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # metrics k8s io api
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "watch", "list"]
  # networking k8s io api
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressesclasses", "networkpolicies"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # policy
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "watch", "list"]
  # rbac.authorization.k8s.io
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles", "rolebindings", "roles"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # impersonation rule
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["impersonate"]
    resourceNames: ["secret-reader", "hks-admin"]
  # otterize
  - apiGroups: ["k8s.otterize.com"]
    resources: ["clientintents"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # certificates
  - apiGroups: ["cert-manager.io"]
    resources: ["certificate"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]
  # certificates
  - apiGroups: ["cert-manager.io"]
    resources: ["certificate"]
    verbs: ["get", "watch", "list", "delete", "patch", "update", "create"]