apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
  # core api
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "services", "events", "nodes", "namespaces", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "watch", "list"]
  # autoscaling api
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "watch", "list"]
  # apps api
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "watch", "list"]
  # batch api
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "watch", "list"]
  # metrics k8s io api
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "watch", "list"]
  # networking k8s io api
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressesclasses"]
    verbs: ["get", "watch", "list"]
  # otterize
  - apiGroups: ["k8s.otterize.com"]
    resources: ["clientintents"]
    verbs: ["get", "watch", "list"]
  # certificates
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "watch", "list"]