apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhook-sink
  name: webhook-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-sink
  template:
    metadata:
      labels:
        app: webhook-sink
    spec:
      {{- if .Values.affinity }}
      affinity: 
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end}}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - image: {{.Values.deployment.image}}
          name: webhook-sink
          resources:
            requests:
              cpu: {{.Values.deployment.resources.requests.cpu}}m
              memory: {{.Values.deployment.resources.requests.memory}}Mi
            limits:
              cpu: {{.Values.deployment.resources.limits.cpu}}m
              memory: {{.Values.deployment.resources.limits.memory}}Mi          
          securityContext: 
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault