apiVersion: v1
kind: Service
metadata:
  name: webhook-sink
  labels:
    app: webhook-sink
spec:
  selector:
    app: webhook-sink
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP