apiVersion: v2
name: victoria-metrics-cluster
version: 1.0.0
description: This Chart deploys victoria-metrics-cluster.
dependencies:
  - name: victoria-metrics-cluster
    version: 0.27.0
    repository: https://victoriametrics.github.io/helm-charts/
  - name: default-netpol
    version: 1.4.1-ac5342
    repository: oci://ghcr.io/hamburg-port-authority/defaultnetpol