# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria-metrics-agent
spec:
  image:
    repository: {{ .Values.image.repository }}
  useStrictSecurity: true
  securityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    promscrape.maxScrapeSize: "167772160"
    promscrape.streamParse: "true"
  additionalScrapeConfigs:
    name: vmagent-additional-scrape-configs
    key: additional-scrape-configs.yaml
  remoteWrite:
    - url: {{ .Values.agent.remoteWriteUrl }}
  scrapeInterval: 10s
  selectAllByDefault: true
  serviceAccountName: victoria-metrics-agent
  replicaCount: 1