image:
  repository: "prom/alertmanager"
  tag: "v0.27.0"
ingress:
  enabled: true
  host: alertmanageer.localhost
  className: nginx
  certificateIssuer: selfsigned
configRawYaml: |
  global:
    resolve_timeout: 5m
  route:
    receiver: 'null'
    group_interval: 5m
    repeat_interval: 12h
  receivers:
    - name: 'null'
extraEnvs: []
tolerations: {}
  # - key: "nodetype"
  #   operator: "Equal"
  #   value: "infrastructurenode"
  #   effect: "NoSchedule"
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: nodetype
  #         operator: In
  #         values:
  #         - infrastructurenode