image:
  repository: "prom/alertmanager"
  tag: "v0.27.0"
ingress:
  enabled: true
  host: alertmanageer.localhost
  className: nginx
  certificateIssuer: selfsigned
tolerations: {}
  # - key: "nodetype"
  #   operator: "Equal"
  #   value: "infrastructurenode"
  #   effect: "NoSchedule"
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: nodetype
  #         operator: In
  #         values:
  #         - infrastructurenode